### ISSUE TITLE
Fatal error: for search wordpress

### ISSUE THREAD

**Issue by web-user** [parisholley/wordpress-fantastic-elasticsearch#152]
I made the settings as it was written here https://ru.wordpress.org/plugins/fantastic-elasticsearch/#installation
I'm testing and I was shown an error 

Fatal error: Uncaught Error: Call to undefined function Elastica\Transport\curl_init() in /home/user/projects/apache/wp-content/plugins/fantastic-elasticsearch/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php:209 Stack trace: #0 /home/user/projects/apache/wp-content/plugins/fantastic-elasticsearch/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php(51): Elastica\Transport\Http->_getConnection(true) #1 /home/user/projects/apache/wp-content/plugins/fantastic-elasticsearch/vendor/ruflin/elastica/lib/Elastica/Request.php(172): Elastica\Transport\Http->exec(Object(Elastica\Request), Array) #2 /home/user/projects/apache/wp-content/plugins/fantastic-elasticsearch/vendor/ruflin/elastica/lib/Elastica/Client.php(627): Elastica\Request->send() #3 /home/user/projects/apache/wp-content/plugins/fantastic-elasticsearch/vendor/ruflin/elastica/lib/Elastica/Search.php(462): Elastica\Client->request('/_search', 'GET', Array, Array) #4 home/user/projects/apache/wp-content/plugins/fantastic-elasticsearch/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php on line 209

**Comment by web-user** [comment]
I found a mistake, need install php curl

**Comment by web-user** [comment]
`sudo apt-get install php-curl`
